package com.company.enums;

public enum Status {
    START, AGE, ENTER_OFFICE_NAME,  ENTER_NAME, TYPE_TECHNOLOGY, PHONE_NUMBER, REGION, PAYMENT, PROFESSION, TIME,
    PURPOSE, CONFIRM_OR_CANCEL, NAME_CHARGE, JOB_TIME, SALARY
}
